
/* Generated by Interface Builder */

#import <Cocoa/Cocoa.h>

@interface StyleToy:NSObject
{
    IBOutlet id	TabForm;
    IBOutlet id	ParameterForm;
    IBOutlet id	StylePanel;
   IBOutlet  id	NameForm;
}

+new;

- loadDefaultStyleSheet;
- (void)setTabForm:anObject;
- (void)setParameterForm:anObject;
- (void)setStylePanel:anObject;
- (void)setNameForm:anObject;
- (IBAction)NextButton:sender;
- (IBAction)FindUnstyledButton:sender;
- (IBAction)ApplyButton:sender;
- (IBAction)heading1Button:sender;
- (IBAction)heading2Button:sender;
- (IBAction)heading3Button:sender;
- (IBAction)heading4Button:sender;
- (IBAction)heading5Button:sender;
- (IBAction)heading6Button:sender;
- (IBAction)normalButton:sender;
- (IBAction)addressButton:sender;
- (IBAction)exampleButton:sender;
- (IBAction)listButton:sender;
- (IBAction)glossaryButton:sender;
- (IBAction)PreviousButton:sender;
- (IBAction)SetButton:sender;
- (IBAction)PickButton:sender;
- (IBAction)ApplyToSimilar:sender;
- (IBAction)open:sender;
- (IBAction)saveAs:sender;
@end
